name: Update Issue Labels Based on Project Status
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  project_card:
    types: [moved]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update labels based on project status
        uses: octokit/graphql-action@v2
        with:
          query: |
            query($issueId: ID!) {
              node(id: $issueId) {
                ... on Issue {
                  projectItems(first: 1) {
                    nodes {
                      fieldValueByName(name: "Status") {
                        ... on ProjectV2ItemFieldSingleSelectValue {
                          name
                        }
                      }
                    }
                  }
                }
              }
            }
          variables: '{"issueId": "${{ github.event.issue.node_id }}"}'
          headers: '{"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"}'
