name: Update Issue Labels from Project
on:
  project_card:
    types: [moved, created]

jobs:
  update-label:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Label
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.payload.project_card.content_url.split('/').pop();
            const columnName = context.payload.project_card.column_name;
            let label = columnName.replace(/\s+/g, '-').toLowerCase();  
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: [label]
            });
